export const INDUSTRIES = [
  "Dentist / Dental Clinic",
  "Medical / GP / Clinic",
  "Chiropractor / Physio",
  "Cosmetic / Aesthetics Clinic",
  "Law Firm / Solicitor",
  "Accountant / Bookkeeper",
  "Financial Advisor / IFA",
  "Real Estate / Lettings Agent",
  "Restaurant / Cafe",
  "Bar / Pub",
  "Hotel / B&B",
  "Plumber",
  "Electrician",
  "Builder / Construction",
  "Roofer",
  "HVAC / Heating Engineer",
  "Landscaper / Gardener",
  "Cleaner / Cleaning Company",
  "Auto Repair / Mechanic",
  "Tyre / MOT Garage",
  "Car Dealer",
  "Hair Salon / Barber",
  "Beauty Salon / Nails",
  "Spa / Massage",
  "Gym / Personal Trainer",
  "Yoga / Pilates Studio",
  "Vet / Veterinary Clinic",
  "Pet Groomer / Boarding",
  "Photographer",
  "Wedding / Event Services",
  "Marketing Agency",
  "IT / Computer Repair",
  "Locksmith",
  "Pest Control",
  "Moving / Removals",
  "Storage Facility",
  "Funeral Services",
  "School / Nursery / Tutor",
  "Retail Shop",
  "Other",
] as const;

export type Industry = (typeof INDUSTRIES)[number];
